// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Infrastructure.Data;

#nullable disable

namespace TaskManager.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TaskManager.Domain.Entities.Comment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("AuthorId").HasColumnType("uniqueidentifier");
                b.Property<string>("Content").IsRequired().HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<Guid>("TaskId").HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("AuthorId");
                b.HasIndex("TaskId");
                b.ToTable("Comments", (string)null);
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.Project", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<Guid>("OwnerId").HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("OwnerId");
                b.ToTable("Projects", (string)null);
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.ProjectTask", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid?>("AssigneeId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
                b.Property<string>("Priority").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("AssigneeId");
                b.HasIndex("ProjectId", "Status");
                b.ToTable("Tasks", (string)null);
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<string>("ReplacedByTokenHash").HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                b.Property<string>("TokenHash").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("TokenHash").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens", (string)null);
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.Role", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Roles", (string)null);
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("Users", (string)null);
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.UserRole", b =>
            {
                b.Property<Guid>("RoleId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("AssignedAt").HasColumnType("datetime2");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("UserRoles", (string)null);
            });

        modelBuilder.Entity("TaskManager.Domain.ValueObjects.Email", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)")
                    .HasColumnName("Email");
                b.HasKey("UserId");
                b.HasIndex("Value").IsUnique();
                b.ToTable("Users");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.Comment", b =>
            {
                b.HasOne("TaskManager.Domain.Entities.User", "Author")
                    .WithMany()
                    .HasForeignKey("AuthorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("TaskManager.Domain.Entities.ProjectTask", "Task")
                    .WithMany("Comments")
                    .HasForeignKey("TaskId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Author");
                b.Navigation("Task");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.Project", b =>
            {
                b.HasOne("TaskManager.Domain.Entities.User", "Owner")
                    .WithMany("OwnedProjects")
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Owner");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.ProjectTask", b =>
            {
                b.HasOne("TaskManager.Domain.Entities.User", "Assignee")
                    .WithMany("AssignedTasks")
                    .HasForeignKey("AssigneeId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.HasOne("TaskManager.Domain.Entities.Project", "Project")
                    .WithMany("Tasks")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Assignee");
                b.Navigation("Project");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("TaskManager.Domain.Entities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.UserRole", b =>
            {
                b.HasOne("TaskManager.Domain.Entities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("TaskManager.Domain.Entities.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Role");
                b.Navigation("User");
            });

        modelBuilder.Entity("TaskManager.Domain.ValueObjects.Email", b =>
            {
                b.HasOne("TaskManager.Domain.Entities.User", null)
                    .WithOne("Email")
                    .HasForeignKey("TaskManager.Domain.ValueObjects.Email", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.Project", b =>
            {
                b.Navigation("Tasks");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.ProjectTask", b =>
            {
                b.Navigation("Comments");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.Role", b =>
            {
                b.Navigation("UserRoles");
            });

        modelBuilder.Entity("TaskManager.Domain.Entities.User", b =>
            {
                b.Navigation("AssignedTasks");
                b.Navigation("Email").IsRequired();
                b.Navigation("OwnedProjects");
                b.Navigation("RefreshTokens");
                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
    }
}
